Repository LabEsUFPA/meuEgresso, pull requests merged in 2023-04, with the labels that each got.

#8 feat: segregando workflows and add test validation
  .github/workflows/sonarcloud.yml
  .github/workflows/test.yml
Labels: In Progress

#10 FEATURE: Projeto inicial front end
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.vue
  frontend/src/assets/vue.svg
  frontend/src/components/HelloWorld.vue
  frontend/src/main.ts
  frontend/src/pages/HomePage.vue
  frontend/src/pages/RouterTest.vue
  frontend/src/router/index.ts
  frontend/src/router/routes.ts
  frontend/src/stories/HelloWorld.stories.ts
  frontend/src/style.css
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement, In Progress

#11 FEATURE: basic front end
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.vue
  frontend/src/assets/vue.svg
  frontend/src/components/HelloWorld.vue
  frontend/src/main.ts
  frontend/src/pages/HomePage.vue
  frontend/src/pages/RouterTest.vue
  frontend/src/router/index.ts
  frontend/src/router/routes.ts
  frontend/src/stories/HelloWorld.stories.ts
  frontend/src/style.css
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement, Done

#26 docs: atualizado modelo de Feature Request
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/duvidas-e-sugestões.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#24 feat: add husky and lint staged
  frontend/package.json
  frontend/src/router/index.ts
Labels: enhancement

#23 22 feature representação do banco de dados
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/config/security/SecurityConfig.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/grupo/GrupoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoPublicDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioPublicDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/AnuncioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ComentarioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ContribuicaoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/CursoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/DepoimentoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoColocaoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoColocaoModelId.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoEmpresaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoEmpresaModelId.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EmpresaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EnderecoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EtniaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/FaixaSalarialModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GrupoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/PesquisaCientificaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/SexoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TipoBolsaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TitulacaoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TrabalhoPublicadoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/audit/Auditable.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/mongo/FatorRiscoMongo.example
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/mongo/QuestionarioMongo.example
Labels: In Progress

#21 [FEATURE] componentes de input
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/decs.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/tab.svg
  frontend/src/components/CustomButton.vue
  frontend/src/components/CustomCheckbox.vue
  frontend/src/components/CustomInput.vue
  frontend/src/components/CustomSelect.vue
  frontend/src/components/FolderSection.vue
  frontend/src/main.ts
  frontend/src/stories/CustomButton.stories.ts
  frontend/src/stories/CustomCheckbox.stories.ts
  frontend/src/stories/CustomInput.stories.ts
  frontend/src/stories/CustomSelect.stories.ts
  frontend/src/stories/FolderSection.stories.ts
  frontend/src/stories/HelloWorld.stories.ts
  frontend/src/style.css
  frontend/src/style.scss
  frontend/tsconfig.json
Labels: enhancement, Done

#39 [FEATURE]: Tela de cadastro de egresso
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/brasão.png
  frontend/src/assets/logo.svg
  frontend/src/assets/textura.svg
  frontend/src/components/CustomButton.vue
  frontend/src/components/CustomCheckbox.vue
  frontend/src/components/CustomInput.vue
  frontend/src/components/CustomSelect.vue
  frontend/src/components/FolderSection.vue
  frontend/src/components/HeaderAndFooter.vue
  frontend/src/main.ts
  frontend/src/pages/CadastroEgresso.vue
  frontend/src/router/routes.ts
  frontend/src/stories/CustomButton.stories.ts
  frontend/tailwind.config.js
Labels: Done

#35 [FEATURE] RF001 - Front-end
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/check.svg
  frontend/src/assets/loading.svg
  frontend/src/components/CustomButton.vue
  frontend/src/components/CustomCheckbox.vue
  frontend/src/components/CustomInput.vue
  frontend/src/components/CustomSelect.vue
  frontend/src/components/HeaderAndFooter.vue
  frontend/src/components/InvalidInsert.vue
  frontend/src/main.ts
  frontend/src/pages/CadastroAdmin.vue
  frontend/src/pages/CadastroEgresso.vue
  frontend/src/pages/CadastroPerfil.vue
  frontend/src/pages/HelloWorld.vue
  frontend/src/pages/HomePage.vue
  frontend/src/pages/PaginaLogin.vue
  frontend/src/router/routes.ts
  frontend/src/stories/CustomButton.stories.ts
  frontend/src/tests/HelloWorld.test.js
  frontend/src/tests/LoginPage.test.js
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: Done, Front-End

#41 revert: prettier configuracoes
  frontend/package.json
Labels: Config

#50 [FEATURE]: RF001 - Front-End
  frontend/src/components/HeaderAndFooter.vue
  frontend/src/components/InvalidInsert.vue
  frontend/src/pages/CadastroAdmin.vue
  frontend/src/pages/CadastroPerfil.vue
  frontend/src/pages/PaginaLogin.vue
  frontend/src/tests/InvalidInsert.test.ts
Labels: Done

#52 [FEATURE]: RF002 - Front-end: Tela de cadastro de egresso
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/Lattes.svg
  frontend/src/assets/svgPaths.json
  frontend/src/components/CustomButton.vue
  frontend/src/components/CustomCheckbox.vue
  frontend/src/components/CustomInput.vue
  frontend/src/components/CustomSelect.vue
  frontend/src/components/HeaderAndFooter.vue
  frontend/src/pages/CadastroEgresso.vue
  frontend/src/tests/CustomButton.test.ts
  frontend/src/tests/CustomCheckbox.test.ts
  frontend/src/tests/CustomInput.test.ts
  frontend/src/tests/CustomSelect.test.ts
  frontend/src/tests/FolderSection.test.ts
Labels: enhancement, Done, Front-End

#53 [FEATURE]: RF003 - Front-end: Permite visualização do perfil
  frontend/package-lock.json
  frontend/src/assets/edit.svg
  frontend/src/assets/lattes.svg
  frontend/src/assets/linkedin-icon.svg
  frontend/src/assets/profile-pic.png
  frontend/src/components/CustomButtonLink.vue
  frontend/src/components/CustomPerfilData.vue
  frontend/src/components/FolderSection.vue
  frontend/src/pages/PerfilEgresso.vue
  frontend/src/router/routes.ts
  frontend/src/tests/CustomButtonLink.test.ts
  frontend/src/tests/CustomPerfilData.test.ts
  frontend/src/tests/HelloWorld.test.ts
  frontend/src/tests/LoginPage.test.ts
  frontend/src/tests/ProfilePage.test.ts
Labels: enhancement, Done, Front-End

#54 test: adicionar nova pipeline CI de teste unitario usando vite
  .github/workflows/front-test.js.yml
Labels: In Progress, Config

#63 feat: add swagger anotation
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/anuncio/AnuncioController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/auth/AuthenticationController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/contribuicao/ContribuicaoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/cota/CotaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/curso/CursoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/depoimento/DepoimentoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoColacaoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoEmpresaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/empresa/EmpresaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/endereco/EnderecoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/etnia/EtniaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/faixasalarial/FaixaSalarialController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/genero/GeneroController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/grupo/GrupoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/pesquisacientifica/PesquisaCientificaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/tipobolsa/TipoBolsaController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/titulacao/TitulacaoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/trabalhopublicado/TrabalhoPublicadoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/usuario/UsuarioController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoPublicDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioAuthDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GrupoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java
Labels: In Progress, Back-End

#65 feat: adiciona retorno do jwt and set cookie
  backend/meuegresso/docker-compose.yml
  backend/meuegresso/docker/Dockerfile.postgres
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/config/security/SecurityConfig.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/auth/AuthenticationController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioAuthDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ContribuicaoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GrupoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TrabalhoPublicadoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/auth/AuthService.java
  backend/meuegresso/src/main/resources/data.sql
  backend/meuegresso/src/main/resources/dump.sql
  backend/meuegresso/src/main/resources/schema
Labels: Done, Back-End

#78 29 feature rf013 validação de dados
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoValidoController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoPublicDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoValidoDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/enumeration/ResponseType.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoValidoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/repository/egresso/EgressoValidoRepository.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/EgressoValidoService.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/impl/EgressoValidoServiceImpl.java
  backend/meuegresso/src/main/resources/data.sql
Labels: Back-End

#79 refactor: adequação dos inputs ao formato da vee-valiate
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/lattesCinza.svg
  frontend/src/components/CustomCheckbox.vue
  frontend/src/components/CustomInput.vue
  frontend/src/components/CustomSelect.vue
  frontend/src/components/CustomTextarea.vue
  frontend/src/pages/CadastroEgresso.vue
  frontend/src/stories/CustomTextarea.stories.ts
  frontend/src/tests/CustomCheckbox.test.ts
  frontend/src/tests/CustomInput.test.ts
  frontend/src/tests/CustomSelect.test.ts
  frontend/src/tests/CustomTextarea.test.ts
  frontend/src/tests/FolderSection.test.ts
Labels: Done, Front-End, refactor, nivel:critico

#83 [REFACTOR]: Alterar Date para LocalDate e LocalDateTime
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/AuditableDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/pesquisacientifica/PesquisaCientificaDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoColacaoDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/pesquisacientifica/PesquisaCientificaDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioAuthDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoColacaoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/PesquisaCientificaModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/audit/Auditable.java
Labels: Done, Back-End, refactor, nivel:baixo

#86 fix: configuração completa do eslint
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/router/index.ts
  frontend/src/router/routes.ts
  frontend/src/stories/CustomButton.stories.ts
  frontend/src/stories/CustomCheckbox.stories.ts
  frontend/src/stories/CustomInput.stories.ts
  frontend/src/stories/CustomSelect.stories.ts
  frontend/src/stories/CustomTextarea.stories.ts
  frontend/src/stories/FolderSection.stories.ts
  frontend/src/tests/CustomButton.test.ts
  frontend/src/tests/CustomCheckbox.test.ts
  frontend/src/tests/CustomInput.test.ts
  frontend/src/tests/CustomPerfilData.test.ts
  frontend/src/tests/CustomSelect.test.ts
  frontend/src/tests/CustomTextarea.test.ts
  frontend/src/tests/FolderSection.test.ts
  frontend/src/tests/InvalidInsert.test.ts
Labels: bug

#70 test: code quality automation check
  .github/workflows/codeql.yml
Labels: Done, Config

#87 Feature rf001 testes usuario
  backend/meuegresso/pom.xml
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/usuario/UsuarioController.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/auth/AuthenticationResponse.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioDTO.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/enumeration/ResponseType.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GrupoModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/grupo/GrupoService.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/grupo/impl/GrupoServiceImpl.java
  backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/usuario/impl/UsuarioServiceImpl.java
  backend/meuegresso/src/main/resources/application-test.yml
  backend/meuegresso/src/test/java/labes/facomp/ufpa/br/meuegresso/controller/usuario/UsuarioControllerTest.java
  backend/meuegresso/src/test/java/labes/facomp/ufpa/br/meuegresso/repository/usuario/UsuarioRepositoryTest.java
  backend/meuegresso/src/test/java/labes/facomp/ufpa/br/meuegresso/service/usuario/impl/UsuarioServiceImplTest.java
Labels: Done, Back-End

#89 [FEATURE]: RF001 - Cadastro de perfil - Integração e testes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@types/index.d.ts
  frontend/src/assets/lattes.svg
  frontend/src/components/InvalidInsert.vue
  frontend/src/main.ts
  frontend/src/pages/CadastroAdmin.vue
  frontend/src/pages/CadastroPerfil.vue
  frontend/src/pages/PaginaLogin.vue
  frontend/src/router/index.ts
  frontend/src/router/routes.ts
  frontend/src/services/api.ts
  frontend/src/store/CadastroPerfilStore.ts
  frontend/src/store/LoginStore.ts
Labels: enhancement, Done, Front-End, Back-End, test, nivel:critico
